services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_HOST}:${RABBITMQ_PORT}:5672" # Standard AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq/mnesia # Persist RabbitMQ data

volumes:
  rabbitmq_data:
